var searchData=
[
  ['scalar_1800',['scalar',['../classcudf_1_1scalar.html',1,'cudf::scalar'],['../structcudf_1_1detail_1_1scalar__factory_1_1scalar.html',1,'cudf::detail::scalar_factory::scalar&lt; T &gt;']]],
  ['scalar_5fdevice_5fview_5fbase_1801',['scalar_device_view_base',['../classcudf_1_1detail_1_1scalar__device__view__base.html',1,'cudf::detail']]],
  ['scalar_5ffactory_1802',['scalar_factory',['../structcudf_1_1detail_1_1scalar__factory.html',1,'cudf::detail']]],
  ['scalar_5fscatterer_1803',['scalar_scatterer',['../structcudf_1_1detail_1_1scalar__scatterer.html',1,'cudf::detail']]],
  ['scandispatcher_1804',['ScanDispatcher',['../structcudf_1_1experimental_1_1detail_1_1ScanDispatcher.html',1,'cudf::experimental::detail']]],
  ['schema_5fentry_1805',['schema_entry',['../structcudf_1_1io_1_1avro_1_1schema__entry.html',1,'cudf::io::avro']]],
  ['schema_5fparser_1806',['schema_parser',['../classcudf_1_1io_1_1avro_1_1schema__parser.html',1,'cudf::io::avro']]],
  ['schemadesc_5fs_1807',['schemadesc_s',['../structcudf_1_1io_1_1avro_1_1gpu_1_1schemadesc__s.html',1,'cudf::io::avro::gpu']]],
  ['schemaelement_1808',['SchemaElement',['../structcudf_1_1io_1_1parquet_1_1SchemaElement.html',1,'cudf::io::parquet']]],
  ['schematype_1809',['SchemaType',['../structcudf_1_1io_1_1orc_1_1SchemaType.html',1,'cudf::io::orc']]],
  ['scoped_5fstream_1810',['scoped_stream',['../structcudf_1_1util_1_1cuda_1_1scoped__stream.html',1,'cudf::util::cuda']]],
  ['scratch_5farr_1811',['scratch_arr',['../structcudf_1_1io_1_1scratch__arr.html',1,'cudf::io']]],
  ['serialtrienode_1812',['SerialTrieNode',['../structSerialTrieNode.html',1,'']]],
  ['simple_5fop_1813',['simple_op',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20max_20_3e_1814',['simple_op&lt; max &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20mean_20_3e_1815',['simple_op&lt; mean &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20min_20_3e_1816',['simple_op&lt; min &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20product_20_3e_1817',['simple_op&lt; product &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20standard_5fdeviation_20_3e_1818',['simple_op&lt; standard_deviation &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20sum_20_3e_1819',['simple_op&lt; sum &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20sum_5fof_5fsquares_20_3e_1820',['simple_op&lt; sum_of_squares &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['simple_5fop_3c_20variance_20_3e_1821',['simple_op&lt; variance &gt;',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1simple__op.html',1,'cudf::experimental::reduction::op']]],
  ['sink_5finfo_1822',['sink_info',['../structcudf_1_1experimental_1_1io_1_1sink__info.html',1,'cudf::experimental::io::sink_info'],['../structcudf_1_1sink__info.html',1,'cudf::sink_info']]],
  ['size_5fof_5fhelper_1823',['size_of_helper',['../structcudf_1_1detail_1_1size__of__helper.html',1,'cudf::detail']]],
  ['snap_5fstate_5fs_1824',['snap_state_s',['../structcudf_1_1io_1_1snap__state__s.html',1,'cudf::io']]],
  ['sort_5fgroupby_5fhelper_1825',['sort_groupby_helper',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1sort_1_1sort__groupby__helper.html',1,'cudf::experimental::groupby::detail::sort']]],
  ['source_5finfo_1826',['source_info',['../structcudf_1_1source__info.html',1,'cudf::source_info'],['../structcudf_1_1experimental_1_1io_1_1source__info.html',1,'cudf::experimental::io::source_info']]],
  ['standard_5fdeviation_1827',['standard_deviation',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::experimental::reduction::op::standard_deviation'],['../structcudf_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::reduction::op::standard_deviation']]],
  ['statistics_5fchunk_1828',['statistics_chunk',['../structcudf_1_1io_1_1statistics__chunk.html',1,'cudf::io']]],
  ['statistics_5fgroup_1829',['statistics_group',['../structcudf_1_1io_1_1statistics__group.html',1,'cudf::io']]],
  ['statistics_5fmerge_5fgroup_1830',['statistics_merge_group',['../structcudf_1_1io_1_1statistics__merge__group.html',1,'cudf::io']]],
  ['statistics_5fval_1831',['statistics_val',['../unioncudf_1_1io_1_1statistics__val.html',1,'cudf::io']]],
  ['stats_1832',['stats',['../structcudf_1_1io_1_1csv_1_1column__parse_1_1stats.html',1,'cudf::io::csv::column_parse']]],
  ['stats_5fcolumn_5fdesc_1833',['stats_column_desc',['../structcudf_1_1io_1_1stats__column__desc.html',1,'cudf::io']]],
  ['stats_5fstate_5fs_1834',['stats_state_s',['../structcudf_1_1io_1_1stats__state__s.html',1,'cudf::io::stats_state_s'],['../structcudf_1_1io_1_1orc_1_1gpu_1_1stats__state__s.html',1,'cudf::io::orc::gpu::stats_state_s']]],
  ['std_5fargs_1835',['std_args',['../structcudf_1_1groupby_1_1sort_1_1std__args.html',1,'cudf::groupby::sort']]],
  ['std_5fvar_5faggregation_1836',['std_var_aggregation',['../structcudf_1_1experimental_1_1detail_1_1std__var__aggregation.html',1,'cudf::experimental::detail']]],
  ['store_5foutput_5ffunctor_1837',['store_output_functor',['../structcudf_1_1detail_1_1store__output__functor.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20_5ft_2c_20true_20_3e_1838',['store_output_functor&lt; _T, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01__T_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20columntype_2c_20true_20_3e_1839',['store_output_functor&lt; ColumnType, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01ColumnType_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5fresult_5ffunctor_1840',['store_result_functor',['../structcudf_1_1experimental_1_1groupby_1_1detail_1_1store__result__functor.html',1,'cudf::experimental::groupby::detail']]],
  ['strdata_5fenc_5fstate_5fs_1841',['strdata_enc_state_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1strdata__enc__state__s.html',1,'cudf::io::orc::gpu']]],
  ['stream_1842',['Stream',['../structcudf_1_1io_1_1orc_1_1Stream.html',1,'cudf::io::orc']]],
  ['string_5fscalar_1843',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fscalar_5fdevice_5fview_1844',['string_scalar_device_view',['../classcudf_1_1string__scalar__device__view.html',1,'cudf']]],
  ['string_5fstats_1845',['string_stats',['../structcudf_1_1io_1_1string__stats.html',1,'cudf::io']]],
  ['string_5fview_1846',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['string_5fview_5fto_5fpair_1847',['string_view_to_pair',['../structcudf_1_1string__view__to__pair.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_1848',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['stringsstatistics_1849',['StringsStatistics',['../structStringsStatistics.html',1,'']]],
  ['stripedictionary_1850',['StripeDictionary',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeDictionary.html',1,'cudf::io::orc::gpu']]],
  ['stripefooter_1851',['StripeFooter',['../structcudf_1_1io_1_1orc_1_1StripeFooter.html',1,'cudf::io::orc']]],
  ['stripeinformation_1852',['StripeInformation',['../structcudf_1_1io_1_1orc_1_1StripeInformation.html',1,'cudf::io::orc']]],
  ['stripestatistics_1853',['StripeStatistics',['../structcudf_1_1io_1_1orc_1_1StripeStatistics.html',1,'cudf::io::orc']]],
  ['stripestream_1854',['StripeStream',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeStream.html',1,'cudf::io::orc::gpu']]],
  ['sum_1855',['sum',['../structcudf_1_1reduction_1_1op_1_1sum.html',1,'cudf::reduction::op::sum'],['../structcudf_1_1experimental_1_1reduction_1_1op_1_1sum.html',1,'cudf::experimental::reduction::op::sum']]],
  ['sum_5fof_5fsquares_1856',['sum_of_squares',['../structcudf_1_1experimental_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::experimental::reduction::op::sum_of_squares'],['../structcudf_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::reduction::op::sum_of_squares']]]
];
