var searchData=
[
  ['base_5fcategory_5ftype_930',['base_category_type',['../classbase__category__type.html',1,'']]],
  ['binaryop_931',['BinaryOp',['../structcudf_1_1binops_1_1compiled_1_1BinaryOp.html',1,'cudf::binops::compiled']]],
  ['bitmask_932',['BitMask',['../classBitMask.html',1,'']]],
  ['bitwise_5fpartitioner_933',['bitwise_partitioner',['../structbitwise__partitioner.html',1,'']]],
  ['bitwiseop_934',['BitwiseOp',['../structcudf_1_1binops_1_1compiled_1_1BitwiseOp.html',1,'cudf::binops::compiled']]],
  ['bitwiseopdispatcher_935',['BitwiseOpDispatcher',['../structcudf_1_1detail_1_1BitwiseOpDispatcher.html',1,'cudf::detail']]],
  ['block_5fdesc_5fs_936',['block_desc_s',['../structcudf_1_1io_1_1avro_1_1block__desc__s.html',1,'cudf::io::avro']]],
  ['blocksumarray_937',['BlockSumArray',['../structBlockSumArray.html',1,'']]],
  ['blocksumpyramid_938',['BlockSumPyramid',['../classBlockSumPyramid.html',1,'']]],
  ['bool8_939',['bool8',['../structcudf_1_1experimental_1_1bool8.html',1,'cudf::experimental']]],
  ['bounds_5fchecker_940',['bounds_checker',['../structcudf_1_1detail_1_1bounds__checker.html',1,'cudf::detail']]],
  ['brotli_5fdictionary_5fs_941',['brotli_dictionary_s',['../structcudf_1_1io_1_1brotli__dictionary__s.html',1,'cudf::io']]],
  ['build_5fstate_5fs_942',['build_state_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1build__state__s.html',1,'cudf::io::orc::gpu']]],
  ['byte_5fstream_5fs_943',['byte_stream_s',['../structcudf_1_1io_1_1parquet_1_1gpu_1_1byte__stream__s.html',1,'cudf::io::parquet::gpu']]],
  ['byterle_5fenc_5fstate_5fs_944',['byterle_enc_state_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1byterle__enc__state__s.html',1,'cudf::io::orc::gpu']]],
  ['bz2_5ffile_5fheader_5fs_945',['bz2_file_header_s',['../structcudf_1_1io_1_1bz2__file__header__s.html',1,'cudf::io']]]
];
