var searchData=
[
  ['scalar_1555',['scalar',['../classcudf_1_1scalar.html',1,'cudf::scalar'],['../structcudf_1_1detail_1_1scalar__factory_1_1scalar.html',1,'cudf::detail::scalar_factory::scalar&lt; T &gt;']]],
  ['scalar_5fdevice_5fview_5fbase_1556',['scalar_device_view_base',['../classcudf_1_1detail_1_1scalar__device__view__base.html',1,'cudf::detail']]],
  ['scalar_5ffactory_1557',['scalar_factory',['../structcudf_1_1detail_1_1scalar__factory.html',1,'cudf::detail']]],
  ['scalar_5fscatterer_1558',['scalar_scatterer',['../structcudf_1_1detail_1_1scalar__scatterer.html',1,'cudf::detail']]],
  ['schema_5fentry_1559',['schema_entry',['../structcudf_1_1io_1_1avro_1_1schema__entry.html',1,'cudf::io::avro']]],
  ['schema_5fparser_1560',['schema_parser',['../classcudf_1_1io_1_1avro_1_1schema__parser.html',1,'cudf::io::avro']]],
  ['schemadesc_5fs_1561',['schemadesc_s',['../structcudf_1_1io_1_1avro_1_1gpu_1_1schemadesc__s.html',1,'cudf::io::avro::gpu']]],
  ['schemaelement_1562',['SchemaElement',['../structcudf_1_1io_1_1parquet_1_1SchemaElement.html',1,'cudf::io::parquet']]],
  ['schematype_1563',['SchemaType',['../structcudf_1_1io_1_1orc_1_1SchemaType.html',1,'cudf::io::orc']]],
  ['scoped_5fstream_1564',['scoped_stream',['../structcudf_1_1util_1_1cuda_1_1scoped__stream.html',1,'cudf::util::cuda']]],
  ['scratch_5farr_1565',['scratch_arr',['../structcudf_1_1io_1_1scratch__arr.html',1,'cudf::io']]],
  ['serialtrienode_1566',['SerialTrieNode',['../structSerialTrieNode.html',1,'']]],
  ['sink_5finfo_1567',['sink_info',['../structcudf_1_1experimental_1_1io_1_1sink__info.html',1,'cudf::experimental::io::sink_info'],['../structcudf_1_1sink__info.html',1,'cudf::sink_info']]],
  ['size_5fof_5fhelper_1568',['size_of_helper',['../structcudf_1_1detail_1_1size__of__helper.html',1,'cudf::detail']]],
  ['snap_5fstate_5fs_1569',['snap_state_s',['../structcudf_1_1io_1_1snap__state__s.html',1,'cudf::io']]],
  ['source_5finfo_1570',['source_info',['../structcudf_1_1experimental_1_1io_1_1source__info.html',1,'cudf::experimental::io::source_info'],['../structcudf_1_1source__info.html',1,'cudf::source_info']]],
  ['standard_5fdeviation_1571',['standard_deviation',['../structcudf_1_1reduction_1_1op_1_1standard__deviation.html',1,'cudf::reduction::op']]],
  ['statistics_5fchunk_1572',['statistics_chunk',['../structcudf_1_1io_1_1statistics__chunk.html',1,'cudf::io']]],
  ['statistics_5fgroup_1573',['statistics_group',['../structcudf_1_1io_1_1statistics__group.html',1,'cudf::io']]],
  ['statistics_5fmerge_5fgroup_1574',['statistics_merge_group',['../structcudf_1_1io_1_1statistics__merge__group.html',1,'cudf::io']]],
  ['statistics_5fval_1575',['statistics_val',['../unioncudf_1_1io_1_1statistics__val.html',1,'cudf::io']]],
  ['stats_1576',['stats',['../structcudf_1_1io_1_1csv_1_1column__parse_1_1stats.html',1,'cudf::io::csv::column_parse']]],
  ['stats_5fcolumn_5fdesc_1577',['stats_column_desc',['../structcudf_1_1io_1_1stats__column__desc.html',1,'cudf::io']]],
  ['stats_5fstate_5fs_1578',['stats_state_s',['../structcudf_1_1io_1_1stats__state__s.html',1,'cudf::io']]],
  ['std_5fargs_1579',['std_args',['../structcudf_1_1groupby_1_1sort_1_1std__args.html',1,'cudf::groupby::sort']]],
  ['store_5foutput_5ffunctor_1580',['store_output_functor',['../structcudf_1_1detail_1_1store__output__functor.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20_5ft_2c_20true_20_3e_1581',['store_output_functor&lt; _T, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01__T_00_01true_01_4.html',1,'cudf::detail']]],
  ['store_5foutput_5ffunctor_3c_20columntype_2c_20true_20_3e_1582',['store_output_functor&lt; ColumnType, true &gt;',['../structcudf_1_1detail_1_1store__output__functor_3_01ColumnType_00_01true_01_4.html',1,'cudf::detail']]],
  ['strdata_5fenc_5fstate_5fs_1583',['strdata_enc_state_s',['../structcudf_1_1io_1_1orc_1_1gpu_1_1strdata__enc__state__s.html',1,'cudf::io::orc::gpu']]],
  ['stream_1584',['Stream',['../structcudf_1_1io_1_1orc_1_1Stream.html',1,'cudf::io::orc']]],
  ['string_5fscalar_1585',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fscalar_5fdevice_5fview_1586',['string_scalar_device_view',['../classcudf_1_1string__scalar__device__view.html',1,'cudf']]],
  ['string_5fstats_1587',['string_stats',['../structcudf_1_1io_1_1string__stats.html',1,'cudf::io']]],
  ['string_5fview_1588',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_1589',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['stringsstatistics_1590',['StringsStatistics',['../structStringsStatistics.html',1,'']]],
  ['stripedictionary_1591',['StripeDictionary',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeDictionary.html',1,'cudf::io::orc::gpu']]],
  ['stripefooter_1592',['StripeFooter',['../structcudf_1_1io_1_1orc_1_1StripeFooter.html',1,'cudf::io::orc']]],
  ['stripeinformation_1593',['StripeInformation',['../structcudf_1_1io_1_1orc_1_1StripeInformation.html',1,'cudf::io::orc']]],
  ['stripestream_1594',['StripeStream',['../structcudf_1_1io_1_1orc_1_1gpu_1_1StripeStream.html',1,'cudf::io::orc::gpu']]],
  ['sum_1595',['sum',['../structcudf_1_1reduction_1_1op_1_1sum.html',1,'cudf::reduction::op']]],
  ['sum_5fof_5fsquares_1596',['sum_of_squares',['../structcudf_1_1reduction_1_1op_1_1sum__of__squares.html',1,'cudf::reduction::op']]]
];
